Repository mundipagg/magento2, pull requests merged in 2019-12, with the labels that each got.

#162 Correcting installments add coupon
  view/frontend/requirejs-config.js
  view/frontend/web/js/action/cancel-coupon.js
  view/frontend/web/js/action/set-coupon-code.js
  view/frontend/web/js/view/payment/method-renderer/billet_creditcard.js
Labels: :ambulance: Hotfix, :bug: Bug

#163 Fix bug when use coupon
  view/frontend/web/js/action/cancel-coupon.js
  view/frontend/web/js/action/set-coupon-code.js
  view/frontend/web/js/view/payment/method-renderer/billet_creditcard.js
  view/frontend/web/js/view/payment/method-renderer/creditcard.js
  view/frontend/web/js/view/payment/method-renderer/two_creditcard.js
Labels: :ambulance: Hotfix, :bug: Bug

#165 Fix installments add coupon
  view/frontend/web/js/action/cancel-coupon.js
  view/frontend/web/js/action/set-coupon-code.js
  view/frontend/web/js/view/payment/method-renderer/two_creditcard.js
Labels: :ambulance: Hotfix, :bug: Bug

#164 Fix storeId on configuration save
  Concrete/Magento2CoreSetup.php
Labels: :bug: Bug, :star: READY

#166 Fix available payment methods
  Observer/PaymentMethodAvailable.php
Labels: :bug: Bug, :star: READY

#169 Adapting recurrence product screen
  Api/ProductSubscriptionApiInterface.php
  Controller/Adminhtml/Plans/SearchProduct.php
  Model/Api/ProductsSubscription.php
  etc/webapi.xml
  view/adminhtml/templates/recurrence/subscriptions/create.phtml
  view/adminhtml/web/js/recurrence.js
Labels: :art: Enhancement, :star: READY

#170 Fix order history with failed message
  Gateway/Transaction/Base/Command/InitializeCommand.php
Labels: :bug: Bug, :star: READY

#168 Create cart conflict recurrence
  Model/CartConflict.php
  Setup/InstallSchema.php
  etc/di.xml
Labels: :sparkles: Feature

#177 Fix bug on js and add try/catch on saveFormData method
  Model/Api/ProductsSubscription.php
  view/adminhtml/web/js/recurrence.js
Labels: :bug: Bug, :star: READY

#176 Adapting plan screens
  Api/ProductPlanInterface.php
  Block/Adminhtml/Recurrence/Plans/Plan.php
  Controller/Adminhtml/Plans/Create.php
  Controller/Adminhtml/Plans/Delete.php
  Model/Api/ProductsPlan.php
  Setup/InstallSchema.php
  Ui/Component/Column/Actions.php
  etc/adminhtml/menu.xml
  etc/webapi.xml
  view/adminhtml/templates/recurrence/plans/create.phtml
  view/adminhtml/ui_component/mundipagg_mundipagg_subscriptions_listing.xml
  view/adminhtml/web/js/recurrence.js
Labels: :sparkles: Feature, :star: READY

#178 Remove custom option when delete a product subscription
  Controller/Adminhtml/RecurrenceProducts/Delete.php
  Helper/ProductSubscriptionHelper.php
  Model/Api/ProductsSubscription.php
Labels: :bug: Bug, :star: READY

#179 Fix some bugs on recurrence webhooks
  Model/CartConflict.php
  Observer/CartAddProductAfterObserver.php
  view/frontend/templates/customer/invoice.phtml
  view/frontend/templates/customer/subscription.phtml
  view/frontend/web/js/action/cancel-coupon.js
  view/frontend/web/js/action/set-coupon-code.js
Labels: :bug: Bug, :star: READY
