Repository mundipagg/magento2, pull requests merged in 2019-02, with the labels that each got.

#47 Fix webhook error http return code
  Model/WebhookManagement.php
Labels: :bug: Bug, :star: READY

#49 Fix address validation observer
  Gateway/Transaction/CreditCard/ResourceGateway/Create/RequestBuilder.php
  Model/MundiPaggConfigProvider.php
  Observer/CustomerAddressSaveBefore.php
  i18n/pt_BR.csv
Labels: :bug: Bug, :star: READY

#51 Bug fix module conflict
  Model/AbstractInstallmentManagement.php
  Model/InstallmentsByBrandAndAmountManagement.php
  Model/InstallmentsByBrandManagement.php
  view/frontend/web/js/view/payment/method-renderer/creditcard.js
Labels: :bug: Bug, :star: READY

#53 Fix default config brand conflict on fresh new install
  Concrete/Magento2CoreSetup.php
Labels: :bug: Bug, :star: READY

#55 Fix active field id
  Model/MundiPaggConfigProvider.php
  etc/adminhtml/system/global.xml
Labels: :bug: Bug, :star: READY

#56 Add maintenance services
  Api/MaintenanceInterface.php
  Concrete/Magento2CoreSetup.php
  Concrete/Magento2PlatformInvoiceDecorator.php
  Concrete/Magento2PlatformOrderDecorator.php
  Concrete/integrityData
  Model/Maintenance.php
  etc/di.xml
  etc/webapi.xml
Labels: :star: READY, feature

#58 Set order as processing when API's response is paid.
  Gateway/Transaction/CreditCard/ResourceGateway/Create/Response/GeneralHandler.php
Labels: :bug: Bug, :star: READY

#59 Set order as pending when API's response is pending
  Gateway/Transaction/CreditCard/ResourceGateway/Create/Response/GeneralHandler.php
Labels: :bug: Bug, :star: READY

#61 Filter taxvat before customer update
  Concrete/Magento2CoreSetup.php
  Helper/CustomerUpdateMundipaggHelper.php
Labels: :bug: Bug, :star: READY

#62 Merge develop into master
  Concrete/Magento2CoreSetup.php
  Concrete/integrityData
  Helper/CustomerUpdateMundipaggHelper.php
  composer.json
  etc/module.xml
Labels: :bookmark: Version update, :star: READY

#63 Fix create token error on IE 11
  view/frontend/web/js/action/creditcard/token.js
  view/frontend/web/js/view/payment/method-renderer/billet_creditcard.js
  view/frontend/web/js/view/payment/method-renderer/creditcard.js
  view/frontend/web/js/view/payment/method-renderer/two_creditcard.js
Labels: :bug: Bug, :star: READY

#64 Merge develop into master
  Concrete/integrityData
  composer.json
  etc/module.xml
  view/frontend/web/js/action/creditcard/token.js
  view/frontend/web/js/view/payment/method-renderer/billet_creditcard.js
  view/frontend/web/js/view/payment/method-renderer/creditcard.js
  view/frontend/web/js/view/payment/method-renderer/two_creditcard.js
Labels: :bookmark: Version update, :star: READY
