Repository mundipagg/magento2, pull requests merged in 2019-05, with the labels that each got.

#86 Saved cards fixes
  Concrete/Magento2CoreSetup.php
  Concrete/Magento2SavedCardAdapter.php
  Controller/Customer/Cards.php
  Controller/Customer/Remove.php
  Model/Ui/BilletCreditCard/ConfigProvider.php
  Model/Ui/CreditCard/ConfigProvider.php
  Model/Ui/TwoCreditCard/ConfigProvider.php
  Setup/UpgradeSchema.php
  i18n/pt_BR.csv
  view/frontend/layout/customer_account.xml
Labels: :bug: Bug, :star: READY

#88 Partial capture fixes
  Concrete/Magento2PlatformInvoiceDecorator.php
  Observer/BilletCreditCardDataAssignObserver.php
  Observer/CreditCardDataAssignObserver.php
  Observer/TwoCreditCardDataAssignObserver.php
Labels: :bug: Bug, :star: READY

#91 Create functional tests structure
  .circleci/config.yml
  .circleci/data/Dockerfile
  README.md
  behat.yml
  features/bootstrap/FeatureContext.php
  features/partialScenarios.feature
Labels: enhancement

#93 Hotfix remove behat
  .circleci/config.yml
  README.md
  behat.yml
  features/bootstrap/FeatureContext.php
  features/partialScenarios.feature
Labels: :ambulance: Hotfix, :star: READY

#94 Detouring customer update to core, if is a Mundipagg customer
  Block/Adminhtml/Order/Charge/Tab/View.php
  Concrete/Magento2PlatformCustomerDecorator.php
  Observer/AdminCustomerBeforeSave.php
Labels: :bug: Bug, :star: READY

#97 Add id to place order buttons
  view/frontend/web/template/payment/billet.html
  view/frontend/web/template/payment/creditcard.html
  view/frontend/web/template/payment/two-creditcard.html
Labels: :art: Enhancement, :star: READY

#98 Fix bug on customer update at mundipagg
  Observer/AdminCustomerBeforeSave.php
Labels: :bug: Bug, :star: READY

#99 Fix statics methods
  Concrete/Magento2CoreSetup.php
  Observer/DataValidateAdmin.php
Labels: :bug: Bug, :star: READY

#101 Fix address validation and add more checks.
  Observer/CustomerAddressSaveBefore.php
  i18n/pt_BR.csv
Labels: :bug: Bug, :star: READY

#102 Link to boleto does not appear
  Block/Payment/Billet.php
  Block/Payment/Info/Billet.php
  Block/Payment/Info/BilletCreditCard.php
  view/frontend/templates/info/billet.phtml
  view/frontend/templates/info/billetCreditCard.phtml
  view/frontend/templates/payment/billet.phtml
  view/frontend/web/template/payment/billet-creditcard.html
Labels: :bug: Bug, :star: READY
