Repository mundipagg/magento2, pull requests merged in 2019-04, with the labels that each got.

#73 Use core implementation of multibuyer and multipayment
  Concrete/Magento2CoreSetup.php
  Concrete/Magento2PlatformOrderDecorator.php
  Controller/Customer/Remove.php
  Gateway/Transaction/Base/Command/InitializeCommand.php
  Model/CardsRepository.php
  Model/Ui/BilletCreditCard/ConfigProvider.php
  Model/Ui/TwoCreditCard/ConfigProvider.php
  Observer/BilletCreditCardDataAssignObserver.php
  Observer/CreditCardDataAssignObserver.php
  Observer/CreditCardOrderPlaceBeforeObserver.php
  Observer/SalesOrderPlaceAfter.php
  Observer/TwoCreditCardDataAssignObserver.php
  view/frontend/web/js/view/payment/bcc-form.js
  view/frontend/web/js/view/payment/two-cc-form.js
Labels: :star: READY, enhancement, feature

#75 Update module core and add missing saved credit card fields on payment table.
  Api/Data/CardsInterface.php
  Concrete/Magento2CoreSetup.php
  Concrete/Magento2PlatformOrderDecorator.php
  Model/Cards.php
  Model/CardsRepository.php
  Model/Ui/CreditCard/ConfigProvider.php
  Observer/CreditCardDataAssignObserver.php
  Observer/DataValidateAdmin.php
  Setup/UpgradeSchema.php
Labels: :bug: Bug, :star: READY

#77 Merge develop into master
  Api/Data/CardsInterface.php
  Concrete/Magento2CoreSetup.php
  Concrete/Magento2PlatformOrderDecorator.php
  Concrete/integrityData
  Model/Cards.php
  Model/CardsRepository.php
  Model/Ui/CreditCard/ConfigProvider.php
  Observer/CreditCardDataAssignObserver.php
  Observer/DataValidateAdmin.php
  Setup/UpgradeSchema.php
  composer.json
  etc/module.xml
Labels: :bookmark: Version update, :bug: Bug

#79 Fix total order canceling
  Observer/OrderCancelAfter.php
Labels: :bug: Bug, :star: READY

#80 Fix module configuration saving
  Concrete/Magento2CoreSetup.php
Labels: :bug: Bug, :star: READY

#82 Hotfix add item code to item request
  Concrete/Magento2PlatformOrderDecorator.php
Labels: :bug: Bug

#84 Fix address index check
  Concrete/Magento2PlatformOrderDecorator.php
  Concrete/integrityData
  Gateway/Transaction/TwoCreditCard/ResourceGateway/Create/RequestBuilder.php
  Observer/CustomerAddressSaveBefore.php
  Observer/OrderCancelAfter.php
  README.md
  composer.json
  etc/module.xml
  i18n/pt_BR.csv
Labels: :bug: Bug, :star: READY

#83 Create cancel and capture charge
  Block/Adminhtml/Order/Charge/Tab/View.php
  Concrete/Magento2PlatformOrderDecorator.php
  Controller/Adminhtml/Charges/Cancel.php
  Controller/Adminhtml/Charges/Capture.php
  Controller/Adminhtml/Charges/ChargeAction.php
  view/adminhtml/layout/sales_order_view.xml
  view/adminhtml/templates/tab/view/order_charge.phtml
Labels: :sparkles: Feature, :star: READY
