Repository mundipagg/magento2, pull requests merged in 2019-11, with the labels that each got.

#148 Create endpoints to send recurrence product data
  Api/ProductPlanInterface.php
  Api/ProductSubscriptionInterface.php
  Block/Adminhtml/Recurrence/Subscriptions/Subscription.php
  Model/Api/ProductsPlan.php
  Model/Api/ProductsSubscription.php
  etc/di.xml
  etc/webapi.xml
  view/adminhtml/templates/recurrence/plans/create.phtml
  view/adminhtml/templates/recurrence/subscriptions/create.phtml
  view/adminhtml/web/css/mundipagg_style.css
  view/adminhtml/web/js/recurrence.js
Labels: :construction: In construction, :sparkles: Feature

#149 Wrong charge amount
  .github/PULL_REQUEST_TEMPLATE.md
  Ui/Component/Listing/Column/BrazilCurrency.php
Labels: :bug: Bug

#151 Wrong charge amount develop
  Ui/Component/Listing/Column/BrazilCurrency.php
Labels: :ambulance: Hotfix, :bug: Bug

#153 Merge develop into master
  .circleci/data/Dockerfile
  Api/InstallmentsManagementInterface.php
  Api/MaintenanceInterface.php
  Block/Adminhtml/Customer/Cards.php
  CONTRIBUTING.md
  Concrete/Magento2PlatformOrderDecorator.php
  Concrete/Magento2SavedCardAdapter.php
  Concrete/integrityData
  Model/ResourceModel/Charges.php
  Ui/Component/Listing/Column/BrazilCurrency.php
  composer.json
  etc/di.xml
  etc/module.xml
  i18n/pt_BR.csv
  test.txt
  view/adminhtml/layout/mundipagg_mundipagg_cards_index.xml
  view/adminhtml/templates/customer/cards.phtml
  view/adminhtml/ui_component/mundipagg_mundipagg_charges_index.xml
Labels: :bug: Bug, :star: READY

#155 Change table column on subscription product admin
  Controller/Adminhtml/Subscriptions/Create.php
  Controller/Adminhtml/Subscriptions/Index.php
  etc/adminhtml/menu.xml
  view/adminhtml/templates/recurrence/plans/create.phtml
  view/adminhtml/templates/recurrence/subscriptions/create.phtml
  view/adminhtml/web/js/recurrence.js
Labels: :bug: Bug, :star: READY

#157 Plan creation
  Block/Adminhtml/Recurrence/Plans/Plan.php
  Concrete/Magento2PlatformProductDecorator.php
  Controller/Adminhtml/Plans/Create.php
  Controller/Adminhtml/Plans/Index.php
  Model/Api/ProductsPlan.php
  Model/ProductsPlan.php
  Setup/InstallSchema.php
  Ui/Component/Column/Actions.php
  Ui/Component/Recurrence/Column/PaymentMethodColumn.php
  Ui/Component/Recurrence/Column/RepetitionsColumn.php
  etc/adminhtml/menu.xml
  i18n/en_US.csv
  i18n/pt_BR.csv
  view/adminhtml/ui_component/mundipagg_mundipagg_plans_listing.xml
Labels: :construction: In construction, :sparkles: Feature

#154 Checkout subscriptions
  Block/Adminhtml/Recurrence/Subscriptions/Subscription.php
  Concrete/Magento2PlatformOrderDecorator.php
  Concrete/integrityData
  Controller/Adminhtml/Plans/SearchProduct.php
  Controller/Adminhtml/Subscriptions/Create.php
  Controller/Adminhtml/Subscriptions/Index.php
  Helper/ProductHelper.php
  Helper/RecurrenceProductHelper.php
  Model/Api/ProductsSubscription.php
  Model/InstallmentsByBrandAndAmountManagement.php
  Observer/CartAddProductAfterObserver.php
  Observer/PaymentMethodAvailable.php
  Setup/InstallSchema.php
  Ui/Component/Recurrence/Column/RepetitionsColumn.php
  composer.json
  etc/adminhtml/menu.xml
  etc/events.xml
  etc/module.xml
  view/adminhtml/templates/recurrence/plans/create.phtml
  view/adminhtml/templates/recurrence/subscriptions/create.phtml
  view/adminhtml/web/js/recurrence.js
Labels: :sparkles: Feature, :star: READY

#158 Create migration magento2
  Setup/InstallSchema.php
Labels: :construction: In construction, :sparkles: Feature

#159 Create recurrence product CRUD API
  Api/ProductSubscriptionApiInterface.php
  Concrete/Magento2DatabaseDecorator.php
  Model/Api/ProductsSubscription.php
  Setup/InstallSchema.php
  Ui/Component/Recurrence/Column/RepetitionsColumn.php
  etc/di.xml
  etc/webapi.xml
Labels: :sparkles: Feature, :star: READY

#160 Create subscription invoice to customer
  Block/Customer/Invoice.php
  Block/Customer/Subscription.php
  Concrete/Magento2DatabaseDecorator.php
  Controller/Customer/Invoice.php
  Controller/Customer/Subscription.php
  i18n/pt_BR.csv
  view/frontend/layout/customer_account.xml
  view/frontend/layout/mundipagg_customer_invoice.xml
  view/frontend/layout/mundipagg_customer_subscription.xml
  view/frontend/templates/customer/invoice.phtml
  view/frontend/templates/customer/subscription.phtml
Labels: :construction: In construction, :sparkles: Feature

#161 Change cart observer rules to set the recurrence price sel…
  Helper/RecurrenceProductHelper.php
  Observer/CartAddProductAfterObserver.php
Labels: :sparkles: Feature, :star: READY
