Repository mundipagg/magento2, pull requests merged in 2019-10, with the labels that each got.

#135 Create menu sidebar recurrence
  Controller/Adminhtml/Recurrence/Plans.php
  Controller/Adminhtml/Recurrence/Subscriptions.php
  etc/adminhtml/menu.xml
Labels: :construction: In construction, :sparkles: Feature

#134 Create recurrence configuration
  Concrete/Magento2CoreSetup.php
  Concrete/integrityData
  Controller/Adminhtml/Recurrence/Plans.php
  Controller/Adminhtml/Recurrence/Subscriptions.php
  composer.json
  etc/adminhtml/menu.xml
  etc/adminhtml/system.xml
  etc/adminhtml/system/recurrence.xml
  etc/module.xml
  view/frontend/web/js/core/checkout/PlatformFormBiding.js
  view/frontend/web/js/core/validators/CustomerValidator.js
Labels: :construction: In construction, :sparkles: Feature

#136 Fix bug in charge page
  Model/ResourceModel/Charges.php
  Ui/Component/Listing/Column/BrazilCurrency.php
  etc/di.xml
  view/adminhtml/ui_component/mundipagg_mundipagg_charges_index.xml
Labels: :bug: Bug, :star: READY

#142 Fix saved credit card verification for not registered customers
  view/frontend/web/js/core/checkout/CreditCardToken.js
  view/frontend/web/js/core/models/CreditCardModel.js
  view/frontend/web/js/core/validators/CreditCardValidator.js
  view/frontend/web/js/core/validators/MultibuyerValidator.js
  view/frontend/web/template/payment/creditcard-form.html
Labels: :bug: Bug, :star: READY

#144 Fix credit card amount check.
  Concrete/Magento2PlatformOrderDecorator.php
Labels: :ambulance: Hotfix, :star: READY

#145 Fix page checkout
  view/frontend/web/js/core/models/BoletoCreditcardModel.js
  view/frontend/web/js/core/models/BoletoModel.js
  view/frontend/web/js/core/models/TwoCreditcardsModel.js
  view/frontend/web/js/core/validators/MultibuyerValidator.js
Labels: :bug: Bug

#140 Fix card page
  Block/Adminhtml/Customer/Cards.php
  Concrete/Magento2SavedCardAdapter.php
  i18n/pt_BR.csv
  view/adminhtml/layout/mundipagg_mundipagg_cards_index.xml
  view/adminhtml/templates/customer/cards.phtml
Labels: :art: Enhancement, :bug: Bug

#146 Create recurrence's migration
  Setup/InstallSchema.php
Labels: :sparkles: Feature, :star: READY

#147 Improve product search
  Controller/Adminhtml/Plans/SearchProduct.php
  view/adminhtml/templates/recurrence/plans/create.phtml
  view/adminhtml/templates/recurrence/subscriptions/create.phtml
  view/adminhtml/web/css/mundipagg_style.css
  view/adminhtml/web/js/recurrence.js
Labels: :art: Enhancement, :star: READY
