Repository mundipagg/magento2, pull requests merged in 2019-01, with the labels that each got.

#21 Toggle card saving
  Gateway/Transaction/CreditCard/Config/Config.php
  Gateway/Transaction/CreditCard/Config/ConfigInterface.php
  Model/Ui/CreditCard/ConfigProvider.php
  etc/adminhtml/system/transaction/creditcard.xml
  view/frontend/web/js/view/payment/bcc-form.js
  view/frontend/web/js/view/payment/cc-form.js
  view/frontend/web/js/view/payment/two-cc-form.js
  view/frontend/web/template/payment/bcc-form.html
  view/frontend/web/template/payment/cc-form.html
  view/frontend/web/template/payment/two-cc-form.html
Labels: :star: READY, enhancement

#24 Cancel order from platform
  Concrete/Magento2CoreSetup.php
  Concrete/Magento2DataService.php
  Concrete/Magento2PlatformOrderDecorator.php
  Observer/OrderCancelAfter.php
  Setup/InstallSchema.php
  Setup/UpgradeSchema.php
  etc/events.xml
  etc/module.xml
Labels: :star: READY, feature

#25 Fix installment calculation
  Concrete/Magento2CoreSetup.php
  Model/AbstractInstallmentManagement.php
  Model/Installments/Builder.php
  Model/Installments/BuilderByBrand.php
  Model/Installments/BuilderByBrandAndAmount.php
  Model/InstallmentsByBrandAndAmountManagement.php
  Model/InstallmentsByBrandManagement.php
  Model/InstallmentsManagement.php
  Setup/UpgradeSchema.php
Labels: :bug: Bug, :star: READY, enhancement

#27 Bug fix on core.
  composer.json
Labels: :bug: Bug, :star: READY

#29 Refact checkout frontend
  view/frontend/web/js/core/checkout/Bin.js
  view/frontend/web/js/core/checkout/PaymentMethodController.js
  view/frontend/web/js/core/checkout/PaymentModuleBootstrap.js
  view/frontend/web/js/core/checkout/PlatformFormBiding.js
  view/frontend/web/js/core/checkout/PlatformFormHandler.js
  view/frontend/web/js/view/payment/cc-form.js
  view/frontend/web/js/view/payment/method-renderer/creditcard.js
  view/frontend/web/js/view/payment/method-renderer/two_creditcard.js
  view/frontend/web/template/payment/cc-form.html
Labels: :bug: Bug, :star: READY

#31 Fix compatibility with legacy code
  Concrete/Magento2PlatformOrderDecorator.php
Labels: :bug: Bug, :star: READY

#33 Fix capture transaction creation.
  Concrete/Magento2PlatformInvoiceDecorator.php
  Observer/SalesOrderPlaceAfter.php
Labels: :bug: Bug, :star: READY

#36 Fix webhook error
  Concrete/Magento2PlatformInvoiceDecorator.php
  Observer/SalesOrderPlaceAfter.php
Labels: :bug: Bug, :star: READY

#37 Fix capture transaction additional info update
  Concrete/Magento2DataService.php
Labels: :bug: Bug, :star: READY

#39 Fix capture transaction compatibility on Magento 2.2.3
  Concrete/Magento2DataService.php
  Concrete/Magento2PlatformInvoiceDecorator.php
Labels: :bug: Bug, :star: READY

#41 Send e-mail on invoice creation.
  Concrete/Magento2PlatformInvoiceDecorator.php
  composer.json
  etc/module.xml
Labels: :bug: Bug, :star: READY

#42 Fix observers when the module is disabled.
  Concrete/Magento2PlatformOrderDecorator.php
  Observer/AdminCustomerBeforeSave.php
  Observer/CustomerAddressSaveBefore.php
  Observer/DataValidateAdmin.php
  Observer/OrderCancelAfter.php
  Observer/SalesOrderPlaceAfter.php
  composer.json
  etc/module.xml
Labels: :bug: Bug, :star: READY

#43 Fix incompatibility with IE
  Model/InstallmentsByBrandAndAmountManagement.php
  Model/InstallmentsByBrandManagement.php
  view/frontend/web/js/action/creditcard/create-card-id.js
  view/frontend/web/js/action/creditcard/customer-create.js
  view/frontend/web/js/action/creditcard/token.js
  view/frontend/web/js/action/installments.js
  view/frontend/web/js/action/installmentsByBrand.js
  view/frontend/web/js/action/installmentsByBrandAndAmount.js
  view/frontend/web/js/action/redirect-after-placeorder.js
  view/frontend/web/js/helper/address-helper.js
  view/frontend/web/js/model/credit-card-validation/credit-card-number-validator.js
  view/frontend/web/js/model/credit-card-validation/credit-card-number-validator/credit-card-type.js
  view/frontend/web/js/view/payment/bcc-form.js
  view/frontend/web/js/view/payment/cc-form.js
  view/frontend/web/js/view/payment/method-renderer/billet.js
  view/frontend/web/js/view/payment/method-renderer/billet_creditcard.js
  view/frontend/web/js/view/payment/method-renderer/creditcard.js
  view/frontend/web/js/view/payment/method-renderer/two_creditcard.js
  view/frontend/web/js/view/payment/payments.js
  view/frontend/web/js/view/payment/two-cc-form.js
Labels: :bug: Bug, :star: READY
