Repository mundipagg/magento2, pull requests merged in 2019-09, with the labels that each got.

#124 Fix bug on saved credit card
  Concrete/Magento2PlatformOrderDecorator.php
Labels: :bug: Bug, :star: READY

#128 Fix bundle product sent to api
  Concrete/Magento2PlatformOrderDecorator.php
Labels: :bug: Bug, :star: READY

#129 Fix duplicated orders
  Concrete/Magento2PlatformOrderDecorator.php
  Gateway/Transaction/Base/Command/InitializeCommand.php
Labels: :bug: Bug, :star: READY

#127 Recreate checkout validations
  Model/Ui/Base/GenericInstallmentsConfigProvider.php
  i18n/en_US.csv
  i18n/pt_BR.csv
  view/frontend/web/js/core/checkout/PaymentMethodController.js
  view/frontend/web/js/core/checkout/PaymentModuleBootstrap.js
  view/frontend/web/js/core/checkout/PlatformFormBiding.js
  view/frontend/web/js/core/checkout/PlatformFormHandler.js
  view/frontend/web/js/core/models/BoletoCreditcardModel.js
  view/frontend/web/js/core/models/BoletoModel.js
  view/frontend/web/js/core/models/CreditCardModel.js
  view/frontend/web/js/core/models/TwoCreditcardsModel.js
  view/frontend/web/js/core/validators/CreditCardValidator.js
  view/frontend/web/js/core/validators/CustomerValidator.js
  view/frontend/web/js/core/validators/MultibuyerValidator.js
  view/frontend/web/js/view/payment/default.js
  view/frontend/web/template/payment/creditcard-form.html
  view/frontend/web/template/payment/multibuyer-form.html
Labels: :construction: In construction, :sparkles: Feature

#126 Recreate credit card boleto feature frontend
  Concrete/Magento2CoreSetup.php
  Concrete/Magento2PlatformOrderDecorator.php
  Concrete/integrityData
  Model/Ui/Base/GenericInstallmentsConfigProvider.php
  Observer/BilletCreditCardDataAssignObserver.php
  Observer/BilletDataAssignObserver.php
  composer.json
  etc/events.xml
  etc/module.xml
  i18n/en_US.csv
  i18n/pt_BR.csv
  view/frontend/web/js/core/checkout/PaymentMethodController.js
  view/frontend/web/js/core/checkout/PaymentModuleBootstrap.js
  view/frontend/web/js/core/checkout/PlatformFormBiding.js
  view/frontend/web/js/core/checkout/PlatformFormHandler.js
  view/frontend/web/js/core/models/BoletoCreditcardModel.js
  view/frontend/web/js/core/models/BoletoModel.js
  view/frontend/web/js/core/models/CreditCardModel.js
  view/frontend/web/js/core/models/TwoCreditcardsModel.js
  view/frontend/web/js/core/validators/CreditCardValidator.js
  view/frontend/web/js/core/validators/CustomerValidator.js
  view/frontend/web/js/core/validators/MultibuyerValidator.js
  view/frontend/web/js/view/payment/boleto.js
  view/frontend/web/js/view/payment/boletocreditcard.js
  view/frontend/web/js/view/payment/default.js
  view/frontend/web/js/view/payment/payments.js
  view/frontend/web/template/payment/boleto-form.html
  view/frontend/web/template/payment/boleto.html
  view/frontend/web/template/payment/boletocreditcard.html
  view/frontend/web/template/payment/creditcard-form.html
  view/frontend/web/template/payment/multibuyer-form.html
Labels: :art: Enhancement, :construction: In construction

#105 Refact module checkout | Primitive methods
  Block/Payment/Info/TwoCreditCard.php
  Concrete/Magento2PlatformOrderDecorator.php
  Model/InstallmentsByBrandAndAmountManagement.php
  Model/Payment.php
  Model/Ui/Base/GenericInstallmentsConfigProvider.php
  Observer/BilletCreditCardDataAssignObserver.php
  Observer/BilletDataAssignObserver.php
  Observer/CreditCardDataAssignObserver.php
  Observer/TwoCreditCardDataAssignObserver.php
  etc/events.xml
  i18n/en_US.csv
  i18n/pt_BR.csv
  view/frontend/web/css/mundipagg_style.css
  view/frontend/web/js/action/installments.js
  view/frontend/web/js/action/installmentsByBrand.js
  view/frontend/web/js/core/checkout/Bin.js
  view/frontend/web/js/core/checkout/CreditCardToken.js
  view/frontend/web/js/core/checkout/Installments.js
  view/frontend/web/js/core/checkout/PaymentMethodController.js
  view/frontend/web/js/core/checkout/PaymentModuleBootstrap.js
  view/frontend/web/js/core/checkout/PlatformFormBiding.js
  view/frontend/web/js/core/checkout/PlatformFormHandler.js
  view/frontend/web/js/core/checkout/PlatformPlaceOrder.js
  view/frontend/web/js/core/models/BoletoCreditcardModel.js
  view/frontend/web/js/core/models/BoletoModel.js
  view/frontend/web/js/core/models/CreditCardModel.js
  view/frontend/web/js/core/models/TwoCreditcardsModel.js
  view/frontend/web/js/core/validators/CreditCardValidator.js
  view/frontend/web/js/core/validators/CustomerValidator.js
  view/frontend/web/js/core/validators/MultibuyerValidator.js
  view/frontend/web/js/view/payment/bcc-form.js
  view/frontend/web/js/view/payment/boleto.js
  view/frontend/web/js/view/payment/boletocreditcard.js
  view/frontend/web/js/view/payment/cc-form.js
  view/frontend/web/js/view/payment/creditcard.js
  view/frontend/web/js/view/payment/default.js
  view/frontend/web/js/view/payment/method-renderer/billet.js
  view/frontend/web/js/view/payment/method-renderer/billet_creditcard.js
  view/frontend/web/js/view/payment/method-renderer/creditcard.js
  view/frontend/web/js/view/payment/method-renderer/two_creditcard.js
  view/frontend/web/js/view/payment/payments.js
  view/frontend/web/js/view/payment/two-cc-form.js
  view/frontend/web/js/view/payment/twocreditcards.js
  view/frontend/web/template/payment/bcc-form.html
  view/frontend/web/template/payment/billet-creditcard.html
  view/frontend/web/template/payment/billet.html
  view/frontend/web/template/payment/boleto-form.html
  view/frontend/web/template/payment/boleto.html
  view/frontend/web/template/payment/boletocreditcard.html
  view/frontend/web/template/payment/cc-form.html
  view/frontend/web/template/payment/creditcard-form.html
  view/frontend/web/template/payment/creditcard.html
  view/frontend/web/template/payment/default.html
  view/frontend/web/template/payment/multibuyer-form.html
  view/frontend/web/template/payment/two-cc-form.html
  view/frontend/web/template/payment/twocreditcards.html
Labels: :art: Enhancement, :construction: In construction

#131 Add phone number to multibuyer form
  Concrete/Magento2PlatformOrderDecorator.php
  Observer/BilletCreditCardDataAssignObserver.php
  Observer/BilletDataAssignObserver.php
  Observer/CreditCardDataAssignObserver.php
  Observer/TwoCreditCardDataAssignObserver.php
  i18n/en_US.csv
  i18n/pt_BR.csv
  view/frontend/web/js/core/checkout/PaymentMethodController.js
  view/frontend/web/js/core/checkout/PlatformFormBiding.js
  view/frontend/web/js/core/checkout/PlatformFormHandler.js
  view/frontend/web/js/core/models/BoletoCreditcardModel.js
  view/frontend/web/js/core/models/BoletoModel.js
  view/frontend/web/js/core/models/CreditCardModel.js
  view/frontend/web/js/core/models/TwoCreditcardsModel.js
  view/frontend/web/js/core/validators/MultibuyerValidator.js
  view/frontend/web/js/view/payment/default.js
  view/frontend/web/template/payment/default.html
  view/frontend/web/template/payment/multibuyer-form.html
Labels: :bug: Bug, :star: READY
