Repository mundipagg/magento2, pull requests merged in 2020-03, with the labels that each got.

#210 Check customer taxvat in guestcustomer
  Concrete/Magento2PlatformOrderDecorator.php
Labels: :art: Enhancement

#212 Create subscription of plan
  Block/Customer/Subscription.php
  Concrete/Magento2PlatformOrderDecorator.php
  Helper/RecurrenceProductHelper.php
  Model/InstallmentsByBrandAndAmountManagement.php
  Ui/Component/Recurrence/Column/TotalCyclesByProduct.php
  etc/adminhtml/menu.xml
Labels: :sparkles: Feature, :star: READY

#213 Fix installments on plan creation
  Helper/RecurrenceProductHelper.php
  view/adminhtml/templates/recurrence/plans/create.phtml
  view/adminhtml/ui_component/mundipagg_mundipagg_plans_listing.xml
Labels: :bug: Bug, :star: READY

#214 Create subscription details page
  Block/Adminhtml/Recurrence/Subscriptions/Subscription.php
  Controller/Adminhtml/Subscriptions/Details.php
  Gateway/Transaction/Base/Command/InitializeCommand.php
  Ui/Component/Column/Subscriptions/Actions.php
  i18n/pt_BR.csv
  view/adminhtml/layout/mundipagg_mundipagg_subscriptions_details.xml
  view/adminhtml/templates/recurrence/subscriptions/details.phtml
Labels: :sparkles: Feature, :star: READY

#215 Recalculing installments
  view/frontend/requirejs-config.js
  view/frontend/web/js/core/checkout/PaymentMethodController.js
  view/frontend/web/js/model/shipping-save-processor-default-mixin.js
Labels: :ambulance: Hotfix, :bug: Bug

#216 Add cancel subscription to details page
  Block/Adminhtml/Recurrence/Subscriptions/Subscription.php
  i18n/pt_BR.csv
  view/adminhtml/templates/recurrence/subscriptions/details.phtml
Labels: :sparkles: Feature, :star: READY

#217 Implementing Voucher Payment Method
  Block/Payment/Info/Voucher.php
  Concrete/Magento2CoreSetup.php
  Concrete/Magento2PlatformOrderDecorator.php
  Concrete/Magento2PlatformPaymentMethodDecorator.php
  Gateway/Transaction/Base/Command/InitializeCommand.php
  Model/Source/Cctype.php
  Model/Source/Vouchertype.php
  Model/Ui/Base/GenericInstallmentsConfigProvider.php
  Model/Ui/Voucher/ConfigProvider.php
  Observer/VoucherDataAssignObserver.php
  etc/adminhtml/system/transaction.xml
  etc/adminhtml/system/transaction/voucher.xml
  etc/adminhtml/system/transaction/voucher/types.xml
  etc/config.xml
  etc/di.xml
  etc/events.xml
  etc/frontend/di.xml
  etc/payment.xml
  view/frontend/layout/checkout_index_index.xml
  view/frontend/web/js/core/checkout/PaymentMethodController.js
  view/frontend/web/js/core/checkout/PlatformFormBiding.js
  view/frontend/web/js/core/checkout/PlatformFormHandler.js
  view/frontend/web/js/core/models/VoucherModel.js
  view/frontend/web/js/view/payment/payments.js
  view/frontend/web/js/view/payment/voucher.js
  view/frontend/web/template/payment/voucher.html
Labels: :sparkles: Feature, :star: READY

#218 Send quantity of subproducts bundle
  Controller/Adminhtml/Plans/SearchProduct.php
  view/adminhtml/web/js/recurrence.js
Labels: :bug: Bug, :star: READY

#219 Fix B2B integration
  view/frontend/web/js/core/checkout/PaymentMethodController.js
  view/frontend/web/js/core/checkout/PlatformFormBiding.js
  view/frontend/web/js/model/shipping-save-processor-default-mixin.js
  view/frontend/web/js/view/payment/default.js
  view/frontend/web/js/view/payment/payments.js
  view/frontend/web/template/payment/boleto-form.html
Labels: :bug: Bug, :star: READY

#220 Implementing update of plans item
  Controller/Adminhtml/Plans/SearchProduct.php
  Helper/ProductPlanHelper.php
  Model/Api/ProductsPlan.php
  Observer/UpdateProductPlanObserver.php
  Setup/UpgradeSchema.php
  etc/events.xml
  view/adminhtml/web/js/recurrence.js
Labels: :sparkles: Feature, :star: READY

#221 Conflict product plan
  Helper/RulesCartRun.php
  Model/Cart/CartConflict.php
Labels: :sparkles: Feature

#222 Fix form checkout broken
  Concrete/Magento2PlatformOrderDecorator.php
  etc/adminhtml/system/transaction/creditcard/installments.xml
  etc/adminhtml/system/transaction/creditcard/installments/alelo.xml
  etc/adminhtml/system/transaction/creditcard/installments/sodexoalimentacao.xml
  etc/adminhtml/system/transaction/creditcard/installments/sodexocombustivel.xml
  etc/adminhtml/system/transaction/creditcard/installments/sodexocultura.xml
  etc/adminhtml/system/transaction/creditcard/installments/sodexogift.xml
  etc/adminhtml/system/transaction/creditcard/installments/sodexopremium.xml
  etc/adminhtml/system/transaction/creditcard/installments/sodexorefeicao.xml
  etc/adminhtml/system/transaction/creditcard/installments/vr.xml
  etc/adminhtml/system/transaction/voucher.xml
  view/frontend/web/js/core/checkout/PaymentModuleBootstrap.js
  view/frontend/web/js/view/payment/boleto.js
  view/frontend/web/js/view/payment/boletocreditcard.js
  view/frontend/web/js/view/payment/creditcard.js
  view/frontend/web/js/view/payment/default.js
  view/frontend/web/js/view/payment/twocreditcards.js
  view/frontend/web/js/view/payment/voucher.js
Labels: :bug: Bug, :star: READY

#223 Payment data details
  Block/Payment/Info/Billet.php
  Block/Payment/Info/BilletCreditCard.php
  Block/Payment/Info/CreditCard.php
  Block/Payment/Info/TwoCreditCard.php
  Setup/UpgradeSchema.php
  i18n/en_US.csv
  i18n/pt_BR.csv
  view/adminhtml/templates/info/billet.phtml
  view/adminhtml/templates/info/billetCreditCard.phtml
  view/adminhtml/templates/info/creditCard.phtml
  view/adminhtml/templates/info/twoCreditCard.phtml
Labels: :art: Enhancement

#224 Update installments when adding coupon
  view/frontend/web/js/action/cancel-coupon.js
  view/frontend/web/js/action/set-coupon-code.js
  view/frontend/web/js/core/checkout/PaymentMethodController.js
Labels: :bug: Bug
