Repository mundipagg/magento2, pull requests merged in 2020-04, with the labels that each got.

#226 Decrease stock every cycle
  Block/Adminhtml/Recurrence/Subscriptions/Subscription.php
  Concrete/Magento2CoreSetup.php
  Concrete/Magento2DatabaseDecorator.php
  Concrete/Magento2PlatformOrderDecorator.php
  Concrete/Magento2PlatformProductDecorator.php
  Controller/Adminhtml/Plans/SearchProduct.php
  Helper/RecurrenceProductHelper.php
  Setup/InstallSchema.php
  etc/adminhtml/system/recurrence.xml
Labels: :sparkles: Feature, :star: READY

#225 Change interfaces adapt swagger
  Api/ObjectMapper/ProductPlan/ProductPlanMapperInterface.php
  Api/ObjectMapper/ProductPlan/SubProduct.php
  Api/ObjectMapper/ProductSubscription/ProductSubscriptionMapperInterface.php
  Api/ObjectMapper/ProductSubscription/RepetitionInterface.php
  Api/ProductPlanApiInterface.php
  Api/ProductSubscriptionApiInterface.php
  Helper/ProductPlanHelper.php
  Model/Api/ProductsPlan.php
  Model/Api/ProductsSubscription.php
  Plugin/Webapi/RestResponse/JsonPlugin.php
  etc/di.xml
Labels: :ambulance: Hotfix, :bug: Bug

#227 Add installation table
  Setup/UpgradeSchema.php
Labels: :ambulance: Hotfix, :star: READY

#229 Save voucher card
  Concrete/Magento2PlatformOrderDecorator.php
  view/frontend/web/js/core/checkout/PaymentMethodController.js
  view/frontend/web/js/core/checkout/PlatformFormHandler.js
  view/frontend/web/template/payment/creditcard-form.html
Labels: :art: Enhancement, :sparkles: Feature

#232 Fix voucher form
  view/frontend/web/template/payment/voucher.html
Labels: :bug: Bug, :star: READY

#231 Fix bug when update and delete subscription product
  Model/Api/ProductsSubscription.php
Labels: :bug: Bug

#233 Check Item is array before loop
  Observer/PaymentMethodAvailable.php
Labels: :ambulance: Hotfix, :bug: Bug

#234 Create Debit Configuration
  Concrete/Magento2CoreSetup.php
  Model/Source/Debittype.php
  etc/adminhtml/system/transaction.xml
  etc/adminhtml/system/transaction/debit.xml
  etc/adminhtml/system/transaction/debit/types.xml
Labels: :construction: In construction, :sparkles: Feature

#236 Saved voucher card and create individual configuration for voucher(saved card)
  Model/Ui/Voucher/ConfigProvider.php
  etc/adminhtml/system/transaction/voucher.xml
  view/frontend/web/js/core/checkout/PaymentMethodController.js
  view/frontend/web/js/core/checkout/PlatformFormBiding.js
  view/frontend/web/js/core/checkout/PlatformFormHandler.js
Labels: :art: Enhancement, :sparkles: Feature

#237 Block buy with disabled brand
  view/frontend/web/js/core/validators/CreditCardValidator.js
Labels: :bug: Bug

#238 Remove Change status label
  etc/adminhtml/system/transaction/creditcard.xml
  etc/adminhtml/system/transaction/multipleactionscreditcardbillet.xml
  etc/adminhtml/system/transaction/multipleactionstwocreditcard.xml
Labels: :art: Enhancement

#239 Create weekly subscription
  Block/Adminhtml/Recurrence/Subscriptions/Subscription.php
  Plugin/Princing/Render/FinalPricePlugin.php
  etc/config.xml
  i18n/pt_BR.csv
  view/adminhtml/templates/recurrence/plans/create.phtml
  view/adminhtml/templates/recurrence/subscriptions/create.phtml
  view/frontend/templates/product/priceFinal.phtml
Labels: :sparkles: Feature, :star: READY

#240 Create debit transactions to Mundipagg
  Block/Adminhtml/Recurrence/Subscriptions/Subscription.php
  Concrete/Magento2PlatformOrderDecorator.php
  Concrete/Magento2PlatformPaymentMethodDecorator.php
  Model/Ui/Voucher/ConfigProvider.php
  Observer/DebitDataAssignObserver.php
  Plugin/Princing/Render/FinalPricePlugin.php
  etc/adminhtml/system/transaction/creditcard.xml
  etc/adminhtml/system/transaction/debit.xml
  etc/adminhtml/system/transaction/multipleactionscreditcardbillet.xml
  etc/adminhtml/system/transaction/multipleactionstwocreditcard.xml
  etc/adminhtml/system/transaction/voucher.xml
  etc/config.xml
  etc/events.xml
  i18n/en_US.csv
  i18n/pt_BR.csv
  view/adminhtml/templates/recurrence/plans/create.phtml
  view/adminhtml/templates/recurrence/subscriptions/create.phtml
  view/frontend/templates/product/priceFinal.phtml
  view/frontend/web/js/core/checkout/PaymentMethodController.js
  view/frontend/web/js/core/checkout/PlatformFormBiding.js
  view/frontend/web/js/core/checkout/PlatformFormHandler.js
  view/frontend/web/js/core/validators/CreditCardValidator.js
  view/frontend/web/template/payment/creditcard-form.html
Labels: :sparkles: Feature, :star: READY

#235 Creating debit form
  Block/Payment/Info/Debit.php
  Concrete/Magento2PlatformOrderDecorator.php
  Concrete/Magento2PlatformPaymentMethodDecorator.php
  Model/Source/Debittype.php
  Model/Ui/Debit/ConfigProvider.php
  Observer/DebitDataAssignObserver.php
  etc/adminhtml/system/transaction/debit.xml
  etc/config.xml
  etc/di.xml
  etc/events.xml
  etc/frontend/di.xml
  etc/payment.xml
  i18n/en_US.csv
  i18n/pt_BR.csv
  view/frontend/layout/checkout_index_index.xml
  view/frontend/web/js/core/checkout/PaymentMethodController.js
  view/frontend/web/js/core/checkout/PlatformFormBiding.js
  view/frontend/web/js/core/checkout/PlatformFormHandler.js
  view/frontend/web/js/core/models/DebitModel.js
  view/frontend/web/js/view/payment/debit.js
  view/frontend/web/js/view/payment/payments.js
  view/frontend/web/template/payment/creditcard-form.html
  view/frontend/web/template/payment/debit.html
Labels: :construction: In construction, :sparkles: Feature

#241 :bug: Fix bug with saved card on debit payment
  view/frontend/web/js/core/checkout/PaymentMethodController.js
  view/frontend/web/js/core/checkout/PlatformFormBiding.js
Labels: :bug: Bug, :star: READY

#243 Disable payments methods(Mundipagg) when the module is disabled
  Observer/PaymentMethodAvailable.php
Labels: :bug: Bug

#244 Fix bug when disabled credit card payment method
  view/frontend/web/js/core/checkout/PaymentMethodController.js
  view/frontend/web/js/core/checkout/PlatformFormBiding.js
  view/frontend/web/js/core/checkout/PlatformFormHandler.js
Labels: :bug: Bug
