Repository mundipagg/magento2, pull requests merged in 2020-02, with the labels that each got.

#201 Just execute observer if the order was made by Mundipagg
  Observer/OrderCancelAfter.php
Labels: :bug: Bug, :star: READY

#200 Currency when get price from product
  Plugin/Princing/Render/FinalPricePlugin.php
Labels: :bug: Bug

#204 Fix bug price when add coupon
  view/frontend/web/js/action/cancel-coupon.js
  view/frontend/web/js/action/set-coupon-code.js
  view/frontend/web/js/core/checkout/PaymentMethodController.js
Labels: :bug: Bug

#203 Customize cart conflict
  Concrete/Magento2CoreSetup.php
  Model/Cart/CartConflict.php
  etc/adminhtml/system/recurrence.xml
  etc/di.xml
  view/adminhtml/web/js/recurrence.js
Labels: :sparkles: Feature, :star: READY

#206 Fix cancel's observer when does have not an order
  Observer/OrderCancelAfter.php
Labels: :bug: Bug, :star: READY

#208 Subscription create break when use product that does not exist
  Helper/ProductSubscriptionHelper.php
  Model/Api/ProductsSubscription.php
Labels: :ambulance: Hotfix, :bug: Bug

#211 Make check in guestcustomer to if exists customertaxvat
  Concrete/Magento2PlatformOrderDecorator.php
Labels: :art: Enhancement
