Repository mundipagg/magento2, pull requests merged in 2020-06, with the labels that each got.

#253 Input card expiring data
  view/frontend/web/js/core/checkout/PaymentMethodController.js
  view/frontend/web/js/core/checkout/PlatformFormHandler.js
Labels: :ambulance: Hotfix, :bug: Bug

#255 Lost installment value when module reloading the payments inputs
  Concrete/integrityData
  composer.json
  etc/module.xml
  view/frontend/web/js/core/checkout/PaymentMethodController.js
  view/frontend/web/js/core/checkout/PlatformFormHandler.js
Labels: :ambulance: Hotfix, :bug: Bug

#256 Reloading installments saved card
  view/frontend/web/js/core/checkout/PlatformFormHandler.js
Labels: :ambulance: Hotfix, :bug: Bug

#252 Add credit card method to admin create order
  .circleci/config.yml
  Block/Adminhtml/Form/Field/CcTypes.php
  Block/Adminhtml/Form/Field/Countries.php
  Block/Adminhtml/Form/Field/CountryCreditCard.php
  Block/Form.php
  Helper/Adminhtml/CheckoutHelper.php
  Observer/CreditCardOrderPlaceBeforeObserver.php
  etc/config.xml
  etc/di.xml
  test.txt
  view/adminhtml/layout/sales_order_create_index.xml
  view/adminhtml/layout/sales_order_create_load_block_billing_method.xml
  view/adminhtml/templates/form/creditcard.phtml
  view/adminhtml/web/js/core/checkout/CreditCardToken.js
  view/adminhtml/web/js/core/checkout/CreditCardValidator.js
  view/adminhtml/web/js/core/checkout/Listeners.js
  view/adminhtml/web/js/core/checkout/PlatformFormBiding.js
  view/adminhtml/web/js/core/models/creditCardModel.js
  view/adminhtml/web/js/payment.js
  view/adminhtml/web/js/recurrence.js
  view/frontend/web/template/payment/default.html
Labels: :sparkles: Feature, :star: READY

#257 Allow creates recurrence virtual product
  Block/Adminhtml/Recurrence/Subscriptions/Subscription.php
Labels: :ambulance: Hotfix, :bug: Bug

#259 Adds holder document number create card token
  view/frontend/web/js/core/checkout/CreditCardToken.js
  view/frontend/web/js/core/models/VoucherModel.js
Labels: :art: Enhancement
