Repository mundipagg/magento2, pull requests merged in 2020-11, with the labels that each got.

#292 [Bugfix] Billing address on checkout
  view/frontend/layout/checkout_index_index.xml
  view/frontend/requirejs-config.js
  view/frontend/web/js/mixin/billing-address-mixin.js
  view/frontend/web/template/payment/default.html
Labels: :art: Enhancement, :bug: Bug

#298 Compatibility with OSC checkout
  view/frontend/requirejs-config.js
  view/frontend/web/js/core/checkout/PaymentMethodController.js
  view/frontend/web/js/model/shipping-save-processor-default-mixin.js
Labels: :bug: Bug, :star: READY

#299 Fix bug on billing address OSC checkout with user guest
  view/frontend/web/js/view/payment/default.js
Labels: :bug: Bug, :star: READY

#300 [Bugfix] Module compatible with Magento 2.4
  Block/Adminhtml/Form/Field/CcTypes.php
  Block/Adminhtml/Form/Field/Countries.php
  Block/Adminhtml/Form/Field/CountryCreditCard.php
Labels: :bug: Bug

#303 [Bugfix] Discount recurrence product
  Observer/CartAddProductAfterObserver.php
Labels: :bug: Bug

#302 [Feature] Magento Pix
  Api/PixRequestDataProviderInterface.php
  Block/Payment/Info/Pix.php
  Block/Payment/Pix.php
  Concrete/Magento2CoreSetup.php
  Concrete/Magento2PlatformOrderDecorator.php
  Concrete/Magento2PlatformPaymentMethodDecorator.php
  Model/Source/PixTypes.php
  Model/Ui/Pix/ConfigProvider.php
  Observer/PaymentMethodAvailable.php
  Observer/PixDataAssignObserver.php
  etc/adminhtml/system/transaction.xml
  etc/adminhtml/system/transaction/pix.xml
  etc/config.xml
  etc/di.xml
  etc/events.xml
  etc/frontend/di.xml
  etc/payment.xml
  view/adminhtml/templates/info/pix.phtml
  view/frontend/layout/checkout_index_index.xml
  view/frontend/layout/checkout_onepage_success.xml
  view/frontend/templates/info/pix.phtml
  view/frontend/templates/payment/pix.phtml
  view/frontend/web/js/core/checkout/PaymentMethodController.js
  view/frontend/web/js/core/checkout/PlatformFormBiding.js
  view/frontend/web/js/core/models/PixModel.js
  view/frontend/web/js/view/payment/payments.js
  view/frontend/web/js/view/payment/pix.js
  view/frontend/web/template/payment/pix-form.html
  view/frontend/web/template/payment/pix.html
Labels: :sparkles: Feature
