Repository mundipagg/magento2, pull requests merged in 2020-10, with the labels that each got.

#287 Fix card name input validation, added more logs
  Concrete/Magento2PlatformInvoiceDecorator.php
  Controller/Adminhtml/Charges/Cancel.php
  Ui/Component/Recurrence/Column/CustomerName.php
  view/frontend/web/js/core/checkout/PaymentMethodController.js
Labels: :bug: Bug

#290 Fix empty amount on multimethods
  view/frontend/web/js/core/checkout/PaymentMethodController.js
Labels: :bug: Bug, hacktoberfest-accepted

#291 Adds terms and conditions checkout
  view/frontend/web/template/payment/default.html
Labels: :art: Enhancement, :sparkles: Feature

#294 Create release notes template
  .github/RELEASE-NOTES-TEMPLATE.md
  CONTRIBUTING.md
Labels: :art: Enhancement, hacktoberfest-accepted

#295 Remove not used files
  .github/RELEASE-NOTES-TEMPLATE.md
  CONTRIBUTING.md
Labels: :art: Enhancement, hacktoberfest-accepted

#297 :sparkles: Add domain message.
  etc/adminhtml/system/global.xml
Labels: :sparkles: Feature, hacktoberfest-accepted

#296 :bug: Fix i18n
  .circleci/data/Dockerfile
  .idea/codeStyles/codeStyleConfig.xml
  Concrete/Magento2CoreSetup.php
  Concrete/Magento2PlatformCreditmemoDecorator.php
  Setup/UpgradeSchema.php
  customer[address]
  release-note-template.md
  shipping[address]
  shipping[description]
  view/adminhtml/templates/form/creditcard.phtml
  view/adminhtml/templates/recurrence/plans/create.phtml
  view/adminhtml/templates/recurrence/subscriptions/details.phtml
  view/adminhtml/ui_component/mundipagg_mundipagg_cards_index.xml
  view/adminhtml/ui_component/mundipagg_mundipagg_charges_index.xml
  view/frontend/web/js/core/checkout/PaymentModuleBootstrap.js
Labels: :bug: Bug, hacktoberfest-accepted
