Repository mundipagg/magento2, pull requests merged in 2020-12, with the labels that each got.

#306 Fix quote validation
  Gateway/Transaction/Base/Command/InitializeCommand.php
Labels: :bug: Bug

#307 Sanitize document number on checkout
  view/frontend/web/js/core/checkout/CreditCardToken.js
Labels: :bug: Bug

#308 Handle sendmail errors
  Concrete/Magento2PlatformOrderDecorator.php
Labels: :art: Enhancement, :bug: Bug

#309 Remove legacy logs
  Controller/Customer/Remove.php
  Gateway/Transaction/Billet/ResourceGateway/Create/RequestBuilder.php
  Gateway/Transaction/Billet/ResourceGateway/Create/Response/GeneralHandler.php
  Gateway/Transaction/BilletCreditCard/ResourceGateway/Capture/RequestBuilder.php
  Gateway/Transaction/BilletCreditCard/ResourceGateway/Capture/Response/GeneralHandler.php
  Gateway/Transaction/BilletCreditCard/ResourceGateway/Create/RequestBuilder.php
  Gateway/Transaction/BilletCreditCard/ResourceGateway/Create/Response/GeneralHandler.php
  Gateway/Transaction/BilletCreditCard/ResourceGateway/Refund/RequestBuilder.php
  Gateway/Transaction/BilletCreditCard/ResourceGateway/Refund/Response/GeneralHandler.php
  Gateway/Transaction/CreditCard/ResourceGateway/Capture/RequestBuilder.php
  Gateway/Transaction/CreditCard/ResourceGateway/Create/RequestBuilder.php
  Gateway/Transaction/CreditCard/ResourceGateway/Create/Response/GeneralHandler.php
  Gateway/Transaction/CreditCard/ResourceGateway/Refund/RequestBuilder.php
  Gateway/Transaction/TwoCreditCard/ResourceGateway/Capture/RequestBuilder.php
  Gateway/Transaction/TwoCreditCard/ResourceGateway/Capture/Response/GeneralHandler.php
  Gateway/Transaction/TwoCreditCard/ResourceGateway/Create/RequestBuilder.php
  Gateway/Transaction/TwoCreditCard/ResourceGateway/Create/Response/GeneralHandler.php
  Gateway/Transaction/TwoCreditCard/ResourceGateway/Refund/RequestBuilder.php
  Gateway/Transaction/TwoCreditCard/ResourceGateway/Refund/Response/GeneralHandler.php
  Helper/Logger.php
  Model/CustomerCreateManagement.php
  Model/WebhookManagement.php
  Observer/SalesOrderPlaceAfter.php
Labels: :art: Enhancement, :star: READY
