Repository mundipagg/magento2, pull requests merged in 2020-08, with the labels that each got.

#272 Fix multistores on magento
  .github/PULL_REQUEST_TEMPLATE.md
  Concrete/Magento2CoreSetup.php
  Model/Validation/GenericValidation.php
Labels: :ambulance: Hotfix, :bug: Bug, :star: READY

#275 Rename wrong function name
  Concrete/Magento2PlatformCreditmemoDecorator.php
Labels: :ambulance: Hotfix

#276 Force conversion to float to avoid error on invoice creation
  Block/Payment/Info/BilletCreditCard.php
Labels: :bug: Bug

#278 Avoid load wrong config
  Concrete/Magento2CoreSetup.php
Labels: :art: Enhancement

#277 Fix interest calculation on update total value
  Model/AbstractInstallmentManagement.php
  Observer/CreditCardOrderPlaceBeforeObserver.php
  view/frontend/web/js/core/checkout/PaymentMethodController.js
  view/frontend/web/js/core/checkout/PlatformFormHandler.js
Labels: :bug: Bug

#279 Fix order page, tid not found
  Block/Payment/Info/BilletCreditCard.php
  Block/Payment/Info/CreditCard.php
  Block/Payment/Info/TwoCreditCard.php
Labels: :ambulance: Hotfix, :bug: Bug
