Repository mundipagg/magento2, pull requests merged in 2020-01, with the labels that each got.

#180 Fix bugs on subscription screen
  Block/Customer/Invoice.php
  Helper/ProductSubscriptionHelper.php
  Observer/PaymentMethodAvailable.php
  Setup/InstallSchema.php
  Ui/Component/Recurrence/Column/RepetitionsColumn.php
  view/adminhtml/ui_component/mundipagg_mundipagg_recurrenceproducts_listing.xml
  view/adminhtml/ui_component/mundipagg_mundipagg_subscriptions_listing.xml
  view/frontend/templates/customer/invoice.phtml
  view/frontend/templates/customer/subscription.phtml
Labels: :bug: Bug, :star: READY

#181 Create subscription at mundipagg
  Block/Payment/Billet.php
  Block/Payment/Info/Billet.php
  Setup/InstallSchema.php
Labels: :sparkles: Feature, :star: READY

#182 Create authentication api
  Concrete/integrityData
  Gateway/Transaction/Base/Command/InitializeCommand.php
  composer.json
  etc/module.xml
  etc/webapi.xml
Labels: :sparkles: Feature, :star: READY

#184 Send email change order status
  Concrete/Magento2CoreSetup.php
  Concrete/Magento2PlatformOrderDecorator.php
  Gateway/Transaction/Base/Config/Config.php
  Gateway/Transaction/Base/Config/ConfigInterface.php
  etc/adminhtml/system/global.xml
  i18n/en_US.csv
  i18n/pt_BR.csv
Labels: :art: Enhancement, :sparkles: Feature

#183 Fix invoice list broken
  Block/Customer/Invoice.php
  Controller/Adminhtml/Subscriptions/Delete.php
  Model/ResourceModel/Invoices/Collection.php
  Ui/Component/Column/Subscriptions/Actions.php
  view/adminhtml/ui_component/mundipagg_mundipagg_invoices_listing.xml
  view/frontend/templates/customer/invoice.phtml
Labels: :bug: Bug, :star: READY

#186 Merge into Master
  Concrete/Magento2CoreSetup.php
  Concrete/Magento2PlatformOrderDecorator.php
  Concrete/integrityData
  Gateway/Transaction/Base/Config/Config.php
  Gateway/Transaction/Base/Config/ConfigInterface.php
  composer.json
  etc/adminhtml/system/global.xml
  etc/module.xml
  i18n/en_US.csv
  i18n/pt_BR.csv
Labels: :art: Enhancement, :bookmark: Version update, :sparkles: Feature

#189 Create api plan
  Api/ProductPlanApiInterface.php
  Helper/ProductHelper.php
  Helper/ProductPlanHelper.php
  Helper/ProductSubscriptionHelper.php
  Model/Api/ProductsPlan.php
  etc/di.xml
  etc/webapi.xml
Labels: :art: Enhancement, :sparkles: Feature

#187 Add recurrence price widget
  Concrete/Magento2CoreSetup.php
  Plugin/Princing/Render/FinalPricePlugin.php
  etc/adminhtml/system/recurrence.xml
  etc/di.xml
  i18n/en_US.csv
  i18n/pt_BR.csv
  view/frontend/templates/product/priceFinal.phtml
Labels: :sparkles: Feature

#188 Create invoice canceling
  Api/InvoiceApiInterface.php
  Controller/Adminhtml/Invoices/Delete.php
  Model/Api/Invoice.php
  Ui/Component/Column/Invoices/Actions.php
  Ui/Component/Column/Invoices/Boleto.php
  Ui/Component/Listing/Column/Translate.php
  etc/di.xml
  etc/webapi.xml
  i18n/pt_BR.csv
  view/adminhtml/ui_component/mundipagg_mundipagg_invoices_listing.xml
  view/adminhtml/ui_component/mundipagg_mundipagg_subscriptions_listing.xml
Labels: :sparkles: Feature, :star: READY

#191 Merge develop into master
  Concrete/Magento2PlatformOrderDecorator.php
  composer.json
Labels: :bug: Bug

#192 Fix bug document vatNumber
  view/frontend/web/js/view/payment/default.js
Labels: :bug: Bug

#193 Change layout widget-price
  i18n/en_US.csv
  i18n/pt_BR.csv
  view/frontend/templates/product/priceFinal.phtml
Labels: :art: Enhancement

#194 Fix get boleto url method
  Block/Payment/Billet.php
  Block/Payment/Info/Billet.php
  Block/Payment/Info/BilletCreditCard.php
Labels: :bug: Bug

#195 Fix change layout options cycle recurrence
  Helper/ProductSubscriptionHelper.php
Labels: :art: Enhancement

#197 Fix recurrence product screen to have the cycles on repetition table
  Controller/Adminhtml/Plans/SearchProduct.php
  view/adminhtml/templates/recurrence/plans/create.phtml
  view/adminhtml/templates/recurrence/subscriptions/create.phtml
  view/adminhtml/web/js/recurrence.js
Labels: :bug: Bug, :star: READY

#196 Change column from product subscription to repetitions table
  Controller/Adminhtml/Plans/SearchProduct.php
  Model/Api/ProductsSubscription.php
  Setup/InstallSchema.php
  etc/webapi.xml
  view/adminhtml/templates/recurrence/plans/create.phtml
  view/adminhtml/templates/recurrence/subscriptions/create.phtml
  view/adminhtml/web/js/recurrence.js
Labels: :bug: Bug, :construction: In construction
