Repository mundipagg/magento2, pull requests merged in 2021-05, with the labels that each got.

#325 Changes required PHP version in readme
  README.md
Labels: :art: Enhancement

#328 Adds new route to cancel charge by id
  Api/ChargeApiInterface.php
  Controller/Adminhtml/Charges/Cancel.php
  Model/Api/Charge.php
  Model/Api/ResponseMessage.php
  etc/di.xml
  etc/webapi.xml
Labels: :sparkles: Feature

#329 Adds Magento_Sales resource and changes httpCode answer to 500
  Model/Api/Charge.php
  etc/webapi.xml
Labels: :bug: Bug

#331 Changes exception response code to 400
  Model/Api/Charge.php
Labels: :art: Enhancement
